name: Coverage

on:
  push:
    branches:
      - "master"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "12"

      - name: Install
        run: npm i

      - name: Run Linter
        run: npm run lint

      - name: Generate Report
        run: npm run cover:ci

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v1
